# docker-compose.yml
version: '3.8'
services:
    db:
        image: "postgres" # use latest official postgres version
        ports:
            - 5432:5432  
        restart: always
        env_file:
            - docker-database.env
        volumes:
            - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
            - ./database/initial_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    pgadmin-compose:
        image: dpage/pgadmin4
        env_file:
            - docker-database.env # configure postgres
        ports: 
            - "16543:80"
        depends_on: 
            - db   
    api:
        build: .
        ports: 
            - "5000:5000"
        environment:
            - BRSS_BACKEND_DB_CONNECTION=postgresql://admin:password@db/bigrss
        volumes:
            - .:/api
        depends_on: 
            - db   

volumes:
    database-data: # named volumes can be managed easier using docker-compose